version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
    networks:
      - app_net
  redis:
    image: redis
    networks:
      - app_net
      - new
volumes:
  logvolume01: {}
networks:
  new:
  legacy:
  app_net:
